- package-lock.json
- package.json
> fix: prepublish npm task

- src/components/Context/Context.tsx
- src/hooks/context/models.ts
- src/messages.tsx
- There were missing arguments message, as per issue #86 
- Updated message files to contain expected error messages
Fixes #86
> fix: update proper error messages

- package-lock.json
- package.json
In my previous PR, I forgot to add Studio to dependencies. It was working because I had it linked with `npm link` on my machine and tests are not failing because... well #106 😅 
#102
> fix: missing studio dependency

- src/models/Context.ts
We are getting feedback from our tools saying we have some `injection sink` issues
This small PR resolves the issues we have.
> fix: fixing some injection sink issues

- package.json
The tests are failing sometimes, we don't know all the reasons the tests might be failing but recently we figured that some tests are failing because they are taking more time than the async timeout that was set to 5s. This PR aims to resolve these issues, currently, all the tests in the development server are passing so no way to understand which tests cases are taking more time than intended. 
It was running fine in ubuntu but was having issues in mac and windows.
> test: increased async test timeout to 10s from 5s

- package-lock.json
- package.json
Since `oclif manifest` command didn't have any way to get logs, this PR is installing a fork version of oclif and adding logs so that we can understand what is going on with the command. 
Forked repo - https://github.com/Souvikns/oclif
adding logs - https://github.com/Souvikns/oclif/blob/main/src/commands/manifest.ts
> fix: move over to forked oclif

- .github/workflows/link-check-cron.yml
- .github/workflows/link-check-pr.yml
Duplicated changes as per https://github.com/asyncapi/.github/pull/155
> chore: update link-check workflow

- package-lock.json
- package.json
- src/commands/convert.ts
- src/global.d.ts
Support 2.4.0 AsyncAPI:
- bump all related dependencies to support 2.4.0 AsyncAPI
Part of https://github.com/asyncapi/spec/issues/735
> feat: support 2.4.0 AsyncAPI

- README.md
- docs/index.md
- docs/installation.md
- docs/introduction.md
- docs/usage.md
This pull request is a continuation of [AsyncAPI pull request #1097](https://github.com/asyncapi/website/pull/1097#issuecomment-1338524232).
> docs: new docs folder created to host the docs for AsyncAPI CLI

- src/commands/generate/models.ts
- test/commands/generate/models.test.ts
- Added `csharpAutoImplement` flag to generate auto-implemented properties for C# models
Fixes #468
> feat: generate auto-implemented properties for C# models 

- package-lock.json
- package.json
fixes https://github.com/asyncapi/cli/issues/491
> fix: bump to latest parser v2.0.0-next-major.16

- .github/workflows/if-nodejs-release.yml
@Souvikns sorry but again need you. Of course, release failed as with my previous PR I updated just one part of the pipeline...
> fix: adjust release pipeline related to npm publishing

- .github/workflows/update-docs-in-website.yml
- docs/index.md
- docs/installation.md
- docs/usage.md
- test/commands/diff.test.ts
- to make sure all works well in the navigation in website, weight of `_section` document cannot be higher than weight of other documents in the same folder
- I also made better headings, sometimes removed the as they were duplicating title
> docs: update weight and sections names

- README.md
- docs/installation.md
- docs/usage.md
Fixs typos in Readme,  installation and usage.
> docs: fix typos 

- README.md
updated link for general AsyncAPI [website](https://www.asyncapi.com/) to [CLI](https://www.asyncapi.com/tools/cli/).
**Related issue(s)** resolves: https://github.com/asyncapi/cli/issues/558
> docs: update link to cli website in readme banner

- src/commands/generate/models.ts
- test/commands/generate/models.test.ts
- add's newtonsoft based model generation support for csharp
Fixes #464
> feat: add csharp newtonsoft based model generation support

- src/commands/generate/models.ts
- test/commands/generate/models.test.ts
- add csharp `System.Text.Json` serialization support with a flag.
- 
- Fixes #465
> feat: add csharp json serialization support

- package.json
- scripts/updateUsageDocs.js
Expanding scope for https://github.com/asyncapi/cli/pull/556
Updating `oclif readme` command into `DEBUG=* oclif readme` for debugging purpose. 
**Related issue(s)** Fixes https://github.com/asyncapi/cli/issues/123
cc: @derberg
> docs: update oclif command 

- .github/workflows/release-docker.yml
Added custom description to release-docker workflow
Discussion pr : #358 
> fix: added custom description

- src/errors/specification-file.ts
- src/models/SpecificationFile.ts
- Improve the validate flag to validate only suitable extensions. Close https://github.com/asyncapi/cli/issues/799  
> feat: added case for the extension to validate the file

- package-lock.json
- package.json
- src/commands/generate/models.ts
This PR updates `@smoya/multi-parser` to last version (`4.0.0`).
> chore: update @smoya/multi-parser to last version

- assets/create-glee-app/templates/tutorial/package-lock.json
- assets/create-glee-app/templates/tutorial/package.json
This PR is updating the version of glee in the template for `create-glee-app`.
https://github.com/asyncapi/glee/pull/582#issuecomment-1822944201
> fix: update glee in template

- assets/create-glee-app/templates/tutorial/docs/asyncapi.md
- assets/create-glee-app/templates/tutorial/package-lock.json
- assets/create-glee-app/templates/tutorial/package.json
- assets/create-glee-app/templates/tutorial/tsconfig.json
> feat: update glee package in template

- package-lock.json
- package.json
This PR updates `oclif` to the latest version.
Is this the right process? Or might it cause any conflicts with other dependencies?
cc @Souvikns
> feat: update oclif to latest version

- .github/workflows/if-nodejs-pr-testing.yml
- .github/workflows/if-nodejs-release.yml
doing it first here to make sure it works, then will rollout to others
> ci: add install step in testing that in the end skips cache

- docs/metrics_collection.md
This PR will update `metrics_collection.md`.
Relates to #1386
> docs: update metrics collection document

- .github/workflows/upload-release-assets.yml
Fixes https://github.com/asyncapi/cli/issues/1433
> fix: upload release assets not working

- Dockerfile
> fix: docker permissions

- docs/context.md
ref: https://github.com/asyncapi/website/pull/3111
> fix: fixed rendering issue of website

- docs/metrics_collection.md
ref:  https://github.com/asyncapi/website/pull/3111
> fix: rendering error of the website

- action.yml
- Update action.yml for release of action purpose.
> fix: update action.yml

- .changeset/nine-parents-juggle.md
- This PR is for testing if changesets release is working properly. #1590 
https://github.com/asyncapi/github-action-for-cli/issues/396
> chore: test changesets release

- docs/usage.md
- src/commands/pretty.ts
- Added short description for pretty command.
Resolves #1577
> docs: added short description for pretty command

- CODEOWNERS
Resolves: #1616 
Currently, i am working as a mentee in the Asyncapi CLI, I have already completed my work in this project that is required in the mentorship. cc @Souvikns
> feat: add myself in codeowner 

- docs/usage.md
- package.json
Improves consistency with other CLI tools that offer both --version and -v options.
Fix: #1646
> feat: added additional version flag -v

- .changeset/chatty-days-trade.md
- docs/architecture.md
- docs/usage.md
Updated docs related to `asyncapi new` command.
Fixes: #1670
> docs: update docs regarding asyncapi new command

- bin/run
- bin/run_bin
- package-lock.json
- package.json
**Title** : Fix oclif Handler and update the oclif/core to latest stable version 
#1694 #1692 
**Description :**  
Fixed the issue of _oclifhandler is not a function_ issue and update the oclif/core to latest stable version
> fix: oclif handler and update oclif/core to latest stable version 

- .changeset/curly-cars-knock.md
- .github/workflows/test-action.yml
- github-action/entrypoint.sh
- package-lock.json
- package.json
- Now action testing utilizes the local CLI to test out stuff instead of installing it.
Release not working
Resolves #1757, #1750, #1747
> feat: fix action testing

- .github/workflows/changeset-utils/index.js
- Me being dumb didn't add break statement to switch 😆 
Related to #1652
> ci: add break to switch statements

- README.md
> fix(docs): update the table content of the cli with architecture of the cli 

- src/apps/api/.do/app.yaml
> ci: change domain type to PRIMARY in app.yaml
