src/constants.ts

- Running integration testing was overwriting the global `.asyncapi` file and it was quite annoying while developing. 
- We basically check if the `NODE_ENV` is `test`, and use `.test.asyncapi` file to do all the testing related operations. 
Fixes #23

test: issue with global .asyncapi file getting overwritten while testing

---

README.md
package-lock.json
package.json
src/CliModels.ts
src/cli.ts
src/components/Context/context.spec.tsx
src/components/Validate/Validate.tsx
src/constants.ts
src/hooks/context/contextService.spec.ts
src/hooks/context/hook.spec.ts
src/hooks/context/hooks.tsx

- As of now we are storing context and we access any context we are using the `--context` flag to load from the contexts. 
- This PR will complete the context store use case and intelligently figure out which specification file to load.  
- aims to autodetect specification file path `asyncapi validate`
Fixes #20

feat: created hook to load spec file

---

src/hooks/context/hooks.tsx

- In `context/hook.tsx` second add context method was not surrounded by `try/catch` block which was causing the error. 
Fixes #36

fix: hide stacktrace for error on unavailable context

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
package-lock.json
package.json

** Description** 
As of now, the readme is very plain and it does not provide much help. 
As a user, I would like to see the following things. 
- How to download the CLI
- If CLI is currently under construction then what features does it currently supports.
- What features does it aim to support
- Documentation and usage examples of all the features currently supported.
- Whom to reach out for any problems or doubt that I might have.
As an open-source contributor, I would like to see the following things. 
- How to setup developer environment
- Where can I get closely involved with the project development process
- Proper roadmap to understanding what issues or features are priority.
- Whom to reach out for any problems or doubts that I might have.

docs: updating the readme

---

src/config/context/index.ts
src/config/context/model.spec.ts
src/config/context/model.ts
src/config/context/service.spec.ts
src/config/context/service.ts

This is the start of the process to [move the context commands under config](https://github.com/asyncapi/cli/issues/37#issuecomment-908137433). In this PR I have focused on updating the `contextService` because of the issue discussed [here](https://github.com/asyncapi/cli/issues/38#issuecomment-912377247). I would like to clarify what I have done here. 
- I have recreated context service but this time decoupling as much as possible. 
- Context does a good job to support the `validate` command as it needs only one spec file path. But to support libraries like [cupid](https://github.com/asyncapi/cupid) and [diff](https://github.com/asyncapi/diff) where more than one spec file path is needed context shall evolve as well. For that, I have created a separate `IContext` …

refactor: updated and decoupled contextService logic

---

package.json
src/help-message.tsx

I'm adding a new line at the end of the `asyncapi --help` command to prevent last line from being mixed with the terminal stuff:
It now looks like this:
I'm also adding the `npm run dev` script to ease development.

fix: add newline at the end of help

---

package.json

The CLI is not working once published. For instance, if you try to install it globally with `npm i -g @asyncapi/cli` and then try to run a command, it will fail with an error similar to the one described below. Everything fails except `--help`, which is probably being rendered from the oclif.manifest.json file.
```
$ asyncapi config context add
Error: Cannot find module '/Users/fmvilas/.nvm/versions/node/v14.15.1/lib/node_modules/@a
syncapi/cli/lib/commands/config/context/add'
Require stack:
- /Users/fmvilas/.nvm/versions/node/v14.15.1/lib/node_modules/@asyncapi/cli/node_modules/
@oclif/config/lib/plugin.js
- /Users/fmvilas/.nvm/versions/node/v14.15.1/lib/node_modules/@asyncapi/cli/node_modules/
@oclif/config/lib/config.js
- …
```

fix: cli not working once published

---

src/commands/new.ts

When user uses the `new` command they are asked for the `filename`. 
If the user does not provide a file extension the file is created.
This PR will check to see if any file extension has been made, and will add `.yaml` onto the filename if no extension has been provided.
Just think it's a slightly better developer experience than allowing them to have files without extensions as async API files.
Related issue #114

feat: adding default file extension for users

---

test/commands/context.test.ts

- Added a test specification for `asyncapi config context current`

test: add test for config current

---

README.md

For some reason, the TOC is not generated in README.md. Just manually creating it in this PR.

docs: fix missing toc

---

src/commands/diff.ts
src/commands/validate.ts
src/flags.ts
src/globals.ts
test/commands/validate.test.ts

- Adds Global Watcher for Specification
#73

feat: add global specification watcher

---

package.json

Trying to fix the issue with `npm prepack` command holding of the gh action and not able to publish. 
Still now clear what is causing the issue, since not much log is present, as of now two action run has failed for this 
- https://github.com/asyncapi/cli/runs/5474535742?check_suite_focus=true 
- https://github.com/asyncapi/cli/runs/5391166652?check_suite_focus=true
I tried running the command separately on my fork and it ran not sure why it is having issues here - https://github.com/Souvikns/cli/runs/5469720664?check_suite_focus=true

fix: issue with prepack command  that blocks release

---

package.json

we need to remove this script. I do not remember why I added it in the first place. This should not run after publishing the package for 2 reasons:
- package is already published, what is the point
- release runs on ubuntu so macOS building will always fail

fix: remove script that should not run on a release on ubuntu

---

CODE_OF_CONDUCT.md
src/commands/validate.ts
src/errors/specification-file.ts
test/commands/convert.test.ts
test/commands/validate.test.ts

- Error handling added when loading a spec file for `validate` command, since this process was not handled before in case of error.
- See also #288

feat: extend error handling in validate command

---

.gitignore
assets/examples/tutorial.yml
scripts/fetch-asyncapi-example.js

The idea of a new example is to have it reflect the same example that is used in docs.
why? so tutorials can have a simple command that reader can use to bootstrap example asyncapi file if they do not have any:
```
asyncapi new --example=tutorial.yml --no-tty
```
Resolve https://github.com/asyncapi/cli/issues/205

feat: add new example to `asyncapi new` command

---

src/commands/generate/models.ts

Implements optional parameters for typescript model generator.
Test results:
Tested various other combinations. Implementation was pretty simple.
Fixes #383

feat: add optional parameters to typescript model generator

---

scripts/fetch-asyncapi-example.js
src/commands/diff.ts
src/commands/generate/models.ts
src/commands/validate.ts
src/global.d.ts
src/utils/parser.ts
test/commands/validate.test.ts
test/specification-avro.yml

- Adds support for RAML, Avro and OpenAPI schemas.
- Adds test for `validate` command with an Avro schema.
- Note: `fetch-asyncapi-example.js` can not reuse `utils/parser.ts`, because it's a JS file, which can't import TS files.
- Thanks to @magicmatatjahu who basically gave [the complete solution](https://github.com/asyncapi/cli/issues/142#issuecomment-1197910374).
Resolves #142

feat: add parser plugins (#142)

---

src/commands/generate/models.ts
test/commands/generate/models.test.ts

- Add `csharpArrayType` flag to pass collection type for C# models.
- Added test case for the same.
Fixes #469

feat: change the collectionType for arrays for C# models

---

.github/workflows/bump-homebrew-formula.yml

Fixes #503 
We cannot wait for https://github.com/asyncapi/cli/pull/512 forever, we need to make sure brew community is no longer affected

ci: update brew release workflow to work on schedule

---

.github/workflows/upload-release-assets.yml
package.json

Was missing the command to rename script from the `package.json` file.

fix: windows installer asset uploads

---

src/commands/generate/models.ts
test/commands/generate/models.test.ts

- Adding C++ support to CLI as Modelina supports C++ model generation
Fixes #571

feat: add C++ model generation support

---

src/commands/generate/models.ts
test/commands/generate/models.test.ts

- adds `csharpHashcode` and `csharpEquals` flags.
- Fixes #467 and #466

feat: add hashcode and equals flags for csharp code generation

---

package.json

related to https://github.com/asyncapi/cli/issues/123#issuecomment-1568505343
all work done by @mhmohona was great, we just forgot that by config it is looking for commands in `/home/runner/work/cli/cli/lib/commands` but `lib` is a folder that is not in repo, it needs to be build with `npm run build`
making it as fix as also recent release was broken because of it we assets were not uploaded

fix: make sure that cli commands generation builds project

---

src/commands/generate/models.ts
src/parser.ts

- Added error logging for invalid specification file
Resolves #616 
Fixes https://github.com/asyncapi/cli/issues/549

feat: helper message for `invalid` specification file during model generation

---

src/commands/diff.ts
src/errors/diff-error.ts
test/commands/diff.test.ts

`diff` command will now show error(with exit code 1) when breaking changes are detected. This is the default behaviour.
There's also a flag `--no-error` you can provide to not show this error.
Ex.
```
diff ./old.yml ./new.yml --no-error
```
The current behaviour is that diff will show error no matter the `type` of changes required. For example, 
```
diff ./old.yml ./new.yml --type=non-breaking
```
will show a breaking change error in case there are breaking changes detected between provided documents. 
None

feat: diff will show error on breaking changes

---

src/commands/bundle.ts
test/commands/bundle/bundle.test.ts

bundle command was unable to output in json format.
The `bundle` command was unable to export to `.json` format as `document.json` returns an object instead of a string. 
https://github.com/asyncapi/cli/blob/a874a1a065cae54b30e20bb1485ca63c1a87427b/src/commands/bundle.ts#L60
Fixes #699

fix: issue with bundle command

---

src/commands/config/context/add.ts

- Adds a new flag `--set-current` / `-s` to the context add command that sets the context on addition
- Tested locally by building the cli
Resolves #726 
See also #751

feat: add flag to set context when it is created

---

src/commands/new/file.ts

- Give a list of available example files present in assets/examples folder  
in the new help command.
- Add example usage for the new help command
Behaviour:
```
$ ./bin/run new --help
Creates a new asyncapi file
USAGE
$ asyncapi new [-h] [-n <value>] [-e <value>] [-s] [-p <value>] [--no-tty]
FLAGS
-e, --example=<value>
name of the example to use. Available examples are:
- simple.yml
- anyof.yml
- application-headers.yml
- correlation-id.yml
- websocket-gemini.yml
- gitter-streaming.yml
- mercure.yml
- not.yml
- operation-security.yml
- oneof.yml
- rpc-client.yml
- rpc-server.yml
- slack-rtm.yml
- tutorial.yml
- streetlights-kafka.yml
- streetlights-operation-security.yml
- streetlights-mqtt.yml
-h, --help
Show CLI help.
-n, --file-name=<value>
name of the file
-p, …
```

feat: list example files in new command help message

---

.github/workflows/bump-homebrew-formula.yml
.github/workflows/update-docs-in-website.yml
.github/workflows/update-docs-on-docs-commits.yml
.github/workflows/upload-release-assets.yml

1. resolves https://github.com/asyncapi/cli/issues/605. One left is https://github.com/asyncapi/cli/pull/675/
2.  solves issues with brew publishing that do not work last 3 weeks https://github.com/asyncapi/cli/actions/runs/6030940883

chore: adjust workflows to follow latest gh actions requirements

---

.asyncapi-cli
.gitignore
package.json
src/models/Context.ts

Fixes https://github.com/asyncapi/cli/issues/751
- now `oclif.manifest.json` is also generated on local. Git ignored, but it will be published to npm as it is explicitly mentioned in package.json `files`
- we read context file using node sync method as the parent function cannot run inside `async` function

fix: read context file sync way when calling context model

---

assets/create-glee-app/templates/default/package.json

The current project generated with `asyncapi new glee` is not working because it's missing the `@types/node` dependency. I'm adding it.
No issue

fix: add @types/node to package.json

---

src/commands/new/file.ts

Close: [Issue 794](https://github.com/asyncapi/cli/issues/794)

feat: add checks to verify Extension of files

---

src/commands/optimize.ts

Correct the log command and name file after executing the optimise command,
Related issue(s)
Fixes https://github.com/asyncapi/cli/issues/764

feat: improve the log and correct the path name using optimise command

---

assets/create-glee-app/templates/default/asyncapi.yaml

`asyncapi new glee` command was creating a new glee project with `2.6.0` version of the spec. This PR is updating the `default` example to have spec `3.0.0` support. 
Fixes #829

fix: update asyncapi document in default glee example

---

scripts/fetch-asyncapi-example.js

- This PR addresses the issue related to the async-api CLI build process failing when encountering invalid examples in the spec repository. It filters out the null values from the exampleList.
- ...
Resolves #994

fix: nullish examples in examples.json

---

.github/workflows/release-chocolatey.yml

- Removes apostrophes from the version in `release-chocolatey` as seen in #1069 
Fixes #1069

chore: remove apostrophes from version in `release-chocolatey`

---

package-lock.json
package.json

The `asyncapi start studio` command was not supporting spec v3.0, This PR updated the studio dependency, and with this, the studio command supports spec v3.
Fixes #1085

feat: update studio to latest version

---

src/commands/generate/models.ts

`JAVA_COMMON_PRESET` was pushed twice to `presets` resulting in duplicate methods
fixes #1038

fix: duplicate methods in presets

---

src/commands/validate.ts
test/integration/validate.test.ts

Exit the `validate` with 1 for failing validations. Failing validations should exit with code 1 so they can be used in CI and also comply with the commands' documentation.
Resolves #861

fix: exit with 1 for failing validations

---

.github/workflows/release-chocolatey.yml

Check if the version to be pushed has already been pushed to the remote.
https://asyncapi.slack.com/archives/CQVJXFNQL/p1710432214064749?thread_ts=1710238071.506779&cid=CQVJXFNQL
**Examples**
- [If a package is not pushed it will build normally](https://github.com/ash17290/cli/actions/runs/8287047957/job/22678466474)
- [Else will skip everything](https://github.com/ash17290/cli/actions/runs/8287051904/job/22678478986)

ci: skip trying to push an already pushed version

---

.github/workflows/upload-release-assets.yml

applying the same fixes as in https://github.com/asyncapi/cli/pull/1340 
I forgot that we have one more workflow that uses windows

fix: trigger release of assets with fixed assets workflow

---

.github/workflows/upload-release-assets.yml
scripts/releasePackagesRename.js

apply fix to asset generation
taken from https://github.com/asyncapi/modelina/pull/1926

fix: trigger another release to get assets published with fix

---

.github/workflows/if-nodejs-pr-testing.yml
package.json

The build process passes the entire ``Test NodeJS PR`` pipeline. 
Fixes #1349

ci: fix assets generation on windows machines

---

src/commands/validate.ts
src/parser.ts

This PR will refactor the spec file's validation status returned by `parser.ts`.
**Related issue(s):**
Relates to https://github.com/asyncapi/cli/pull/877

refactor: add enum for spec file's validation status

---

src/commands/convert.ts
src/commands/new/file.ts
src/commands/new/glee.ts
src/models/Studio.ts
src/parser.ts
test/integration/convert.test.ts
test/integration/new/file.test.ts
test/integration/new/glee.test.ts
test/integration/validate.test.ts

- This PR aims to implement the new design system for the `new` command.
**Proof of work**
Fixes #1379
Fixes #1381
Fixes #1385

chore: apply design system to `new` and `convert` command

---

src/commands/generate/fromTemplate.ts

with current code we get https://github.com/asyncapi/nodejs-template/issues/215#issuecomment-2098550341 error
nodejs template already supports v3: https://github.com/asyncapi/nodejs-template/releases/tag/v3.0.0
joava template as well: https://github.com/asyncapi/java-template/releases/tag/v0.3.0

fix: enable to use nodejs and java templates with asyncapi v3

---

src/commands/generate/fromTemplate.ts

Fixes https://github.com/asyncapi/cli/issues/1425

fix: template generation failing

---

test/integration/bundle/bundle.test.ts

This PR will add more verbosity to the tests executed for `bundle` command.
Resolves #1445

test: improve log of tests executed for bundle command

---

test/integration/config/analytics.test.ts

This PR will allow to set up the env var `ASYNCAPI_METRICS_CONFIG_PATH` to a known and controlled config file path instead of using the one located in ~home.
Relates to #1427

test: handle a different analytics config file for testing

---

src/commands/config/analytics.ts
src/commands/diff.ts
src/commands/new/glee.ts
src/commands/start/studio.ts

This PR will add metadata to the following commands:
Resolves #1357

feat: add metadata for some remaining commands

---

src/commands/generate/models.ts

Removing the check for spec v3 as now modelina support AsyncAPI spec v3.
See also https://github.com/asyncapi/cli/pull/1376

fix: modelina supporting asyncapi v3

---

docs/installation.md
package-lock.json
package.json
test/integration/bundle/feature.yaml
test/integration/bundle/final-asyncapi.yaml
test/integration/bundle/first-asyncapi.yaml
test/integration/bundle/first-asyncapiv3.yaml

This PR updates the `@asyncapi/bundler` package to version `0.6.0`.

fix: update package `@asyncapi/bundler` to version `0.6.1`

---

assets/create-glee-app/templates/default/package-lock.json
assets/create-glee-app/templates/default/package.json
assets/create-glee-app/templates/tutorial/package-lock.json
assets/create-glee-app/templates/tutorial/package.json
package-lock.json
package.json

This PR is a clone of https://github.com/asyncapi/cli/pull/1503 created just to pass the frozen automerge mechanism.

fix: update @asyncapi/optimizer to 1.0.3 version and others

---

.github/workflows/upload-release-assets.yml

Oclif v4 needs nodejs v20+ to generate assets. This PR is updating the release workflow to install nodejs 20 for windows.

fix: windows asset release

---

src/core/parser.ts

- Added additional output flag param ```-o``` to output diagnostics log to a file.
- By default the diagnostics log will be printed in terminal.
Resolves #1095

feat: implemented logic to output diagnostics log by adding additional output flag to validate cli command.

---

.changeset/config.json
.github/workflows/release-with-changesets.yml
Development.md

This PR targets adding a changeset configuration for cli and gitHub action for cli.  

feat: added changeset configuration

---

.changeset/bright-cars-raise.md
README.md
package.json

fix: updated README with Development file

---

.changeset/prep-action.md
action.yml

Changing name of the action as apparently name should be unique.

fix: prepare action for release

---

package-lock.json
src/commands/generate/models.ts

- Added a try catch to stop spinner if `Error` is throw by `generateModels()` func.
Resolves #1607

fix: resolved faulty spinner loading after error in console

---

docs/architecture.md
docs/context.md
docs/metrics_collection.md
docs/usage.md

Closes: #1569 
Related: #1508 
* Updated the parameters of various commands to enable proxySupport. [Done]
* Create a new documentation regarding the architecture of the CLI [ Done ]

docs: updating the docs of the cli 

---

docs/usage.md
src/commands/new/file.ts

Resolves #1624
- Updated the help message for the `asyncapi new file -h` command.
- Modified the `usage.md` file to reflect the correct command syntax and example.
@derberg please review this PR

feat: update help message and usage information for asyncapi new file -h

---

src/core/base.ts

Resolves  #1625 
This PR helps to fix the ERROR message issue in the -h help command flag.
Upon going through the  codebase i first tried to log more of error message and got the following for stack trace of the error message.
With referring to above trace and going through the oclif codebase i found that the error being shown here is not an actual error but just used to terminate the help command.
[This is that particular code.](https://github.com/oclif/core/blob/64e680d969b1c316459cb7fae50e70309435686b/src/flags.ts#L176)
Then after carefully going through help command implementation in the oclif codebase and also referring to an already mentioned [old issue](https://github.com/forcedotcom/cli/issues/589) about this bug and their …

fix: remove an error at the end of the -h "help" flag

---

docs/usage.md
package-lock.json
src/commands/start/studio.ts
src/core/flags/start/studio.flags.ts
src/core/models/Studio.ts

Remove -f flag from asyncapi start command 
asyncapi start command can now work without filename also
Fixes #1623 
Case 1 Filename given in command by user.
Case 2 Filename not given in command by user but asyncapi.yaml default file is present in current working directory.
Case 3 Filename not given in command by user and asyncapi.yaml default file is not present in current working directory. Open studio with empty file.
Studio for Case 3

feat: remove -f flag from asyncapi start command

---

.changeset/rude-pets-begin.md
action-template.yml
src/commands/start/studio.ts
src/core/flags/start/studio.flags.ts
src/core/models/Studio.ts

fix: deprecate --file and add release

---

.changeset/five-moles-care.md
src/core/models/Studio.ts

This PR introduces the changes of the UI/UX of the `asyncapi start studio` output. 
The changes are done taking in account the previous PR #1524.
Resolves #1384 
After changes the new output is shown as in below:-
@AayushSaini101 Please review.

chore: added UI/UX improvements to start command

---

.changeset/five-moles-care.md
src/commands/config/analytics.ts
src/commands/config/context/add.ts
src/commands/config/context/current.ts
src/commands/config/context/edit.ts
src/commands/config/context/init.ts
src/commands/config/context/list.ts
src/commands/config/context/remove.ts
src/commands/config/context/use.ts
src/commands/config/versions.ts
test/integration/config/analytics.test.ts
test/integration/context.test.ts

This PR implements the UI/UX improvements to the config command.
The changes are based on the previous [PR](https://github.com/asyncapi/cli/pull/1518)
Tests are also updated for the same.
Resolves  #1380 
Below are attached changes result to the command :-
`config versions`
`config analytics`
`config analytics -s`
`config context init .`
` config context current`
`config context add test-context .`
`config context use test-context`
`config context current`
` config context edit test-context ./`
`config context list`
`config context remove test-context`
@AayushSaini101 please review.
Thanks.

chore: config command  UI/UX improvement.

---

.changeset/wild-rockets-care.md
src/commands/new/file.ts

This PR introduces the changes to fix the starting of studio when used with an example while creating a new file.
Approach:-
Upon debugging found that to start studio the extension had also to be passed with file name so that was added to be passed if not passed by default. `yaml` was passed as it was default extension used by cli when creation of files if no extension is specified.
Resolves #1648

fix: starting of studio fixed when using example with new file

---

.changeset/cuddly-files-move.md
docs/usage.md
src/commands/new/index.ts
test/integration/new/file.test.ts

Made `asyncapi new` command consistent with other commands like `asyncapi generate`.
Fixes: #1647

chore: change the implementation of new command

---

.changeset/quick-pandas-stare.md
docs/usage.md
src/commands/generate/fromTemplate.ts
src/commands/generate/models.ts
test/integration/generate/fromTemplate.test.ts
test/integration/generate/models.test.ts

The following PR introduces the changes required to add the proxy support for the generate command. The tests and docs are also updated for the same. The feature is implemented as flags.
Below are the attached screenshots of the changes.
Resolves #1621 
@AayushSaini101 please review the PR and provide feedback.
Thanks.

feat: added proxy support for the generate commands.

---

.changeset/smooth-rabbits-occur.md
docs/usage.md
src/commands/convert.ts
src/commands/optimize.ts
src/commands/validate.ts

This PR introduces the changes to remove`proxyHost` and `proxyPort` form the arguments of commands `optimize` , `validate` , `convert`.
Docs for the same are also updated.
`optimize`
`convert`
`validate`
All tests are also passing
Resolves #1667 
@AayushSaini101 Please review and provide feedback.
Thanks

fix: proxy implementation for optimize validate and convert fixed

---

docs/architecture.md

On the [page](https://www.asyncapi.com/docs/tools/cli/architecture) extra (*) is shown. The issue was create in asyncapi/website and after approval I created the PR.
fixes: [#3643](https://github.com/asyncapi/website/issues/3643)

docs: inconsistent formatting asterisk-mark

---

.changeset/sour-clouds-heal.md
src/commands/generate/models.ts
test/integration/generate/models.test.ts

`asyncapi generate models LANGUAGE FILE` can print the output in CLI itself if `-o` flag is missing.
Fixes: #1654

fix: print in cli  asyncapi generate models without -o flag

---

docs/usage.md
src/commands/generate/fromTemplate.ts

Made the 2 args for command `asyncapi generate fromTemplate` not required to make the CLI more user-friendly, aligning it with common interactive CLI patterns.
Users will be able to run `asyncapi generate fromTemplate` without needing to remember or type the required arguments.
Fixes #1660

feat: asyncapi generate fromTemplate can now work in interactive mode

---

.changeset/blue-seas-destroy.md
.gitignore
assets/examples/default-example.json
src/commands/new/file.ts

- Added `default-example.json` file, which will be displayed as the default JSON example.
- Used AsyncAPI Studio to convert `default-example.yaml` into JSON format.
- Ensured the JSON file accurately reflects the structure and content of the original YAML file.
Resolves #1710

chore: json file supported in asyncapi new file command

---

.changeset/free-dodos-matter.md
.changeset/stupid-beans-kick.md
package-lock.json
package.json

- Studio was not working as there was no `next.config.js` packaged in the build. Now it has been added leading to requirement of a manual bump.
Fixes #1718

fix: studio command not working

---

.changeset/forty-apples-fix.md
src/core/hooks/command_not_found/myhook.ts

**Title** : Wrong Error message in -h command #1725 
**Description** : This pr will fix the issue of wrong error message which was shown after entering a invalid command 
**Before** : 
**After** :

fix: wrong error message in -h command #1725

---

.changeset/breezy-pandas-arrive.md
docs/usage.md
package-lock.json
src/commands/new/template.ts
src/core/flags/new/template.flags.ts

Remove --renderer flag from asyncapi new template command because only React engine is allowed nunjucks is deprecated.
Below is screenshot of working - 
Fixes #1738

feat: remove --renderer flag from asyncapi new template command

---

.changeset/blue-monkeys-call.md
docs/usage.md
package-lock.json
package.json
src/commands/start/preview.ts
src/core/flags/start/preview.flags.ts
src/core/models/Preview.ts

This PR introduces the changes to implement the new command `asyncapi start preview` to open the studio in a minimal `readOnly` mode along with bundling the ref files internally. An argument to file needs to be passed that is to be opened.
Approach :-
- First after the path to file is passed it is first validated that the file exist. After the validation is complete then using the function `findPathsToWatchFromSchemaRef` the path to ref files are extracted.
- This function uses a stack data structure based approach instead of recursion based as in the later one in case of very large schemas memory consumption will be too much and may cause overflow issues. This makes it not optimal to be implemented hence using stack based approach to get all the path to `ref` files from …

feat: new command `asyncapi start preview` implemented.

---

.github/workflows/auto-changeset.yml
.github/workflows/changeset-utils/index.js
temp-package.json

This pull request introduces an automated workflow for generating changesets for pull requests. The most important changes include the addition of a new GitHub Actions workflow and utility functions to handle changeset generation and commenting on pull requests.
* [`.github/workflows/auto-changeset.yml`](diffhunk://#diff-ff8bc9ad708f80ded673a997bad71c3771c8c1c1d0fc313cdf72d9c31e120e08R1-R79): Added a new workflow to automate changeset generation for pull requests with specific titles. This workflow runs on various pull request events and includes steps for checking out the repository, installing dependencies, generating changeset contents, creating and committing the changeset file, pushing the changeset file, and commenting on the pull request.
* …

ci: add changeset automation

---

.github/workflows/release-server-api.yml

- Turns out GitHub caching doesnot work well with buildkit. https://github.com/moby/buildkit/issues/2804

ci: simplify caching configuration in release workflow
